-- EventHub baseline schema: events + tags.
-- Search vector (FTS), auth, bookmarks, and notifications arrive in later phases.

CREATE TABLE events (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title             VARCHAR(500) NOT NULL,
    description       TEXT,
    source            VARCHAR(50)  NOT NULL,
    source_event_id   VARCHAR(255) NOT NULL,
    category          VARCHAR(40)  NOT NULL,
    organizer         VARCHAR(255),
    start_date_time   TIMESTAMPTZ  NOT NULL,
    end_date_time     TIMESTAMPTZ,
    registration_url  VARCHAR(1000),
    location          VARCHAR(500),
    online            BOOLEAN      NOT NULL DEFAULT FALSE,
    dedup_hash        VARCHAR(64)  NOT NULL,
    status            VARCHAR(20)  NOT NULL DEFAULT 'UPCOMING',
    created_at        TIMESTAMPTZ  NOT NULL,
    updated_at        TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_events_source_native_id UNIQUE (source, source_event_id)
);

CREATE TABLE event_tags (
    event_id BIGINT      NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    tag      VARCHAR(100) NOT NULL,
    PRIMARY KEY (event_id, tag)
);

-- Cross-source duplicate lookups.
CREATE INDEX idx_events_dedup_hash ON events (dedup_hash);

-- Common browse/filter access paths.
CREATE INDEX idx_events_start        ON events (start_date_time);
CREATE INDEX idx_events_category     ON events (category);
CREATE INDEX idx_events_status_start ON events (status, start_date_time);
