-- Run log for each per-source ingestion attempt.
-- Powers the admin "Scheduler Monitoring" screen and the "Failed Ingestion Jobs" metric.

CREATE TABLE ingestion_jobs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source        VARCHAR(50)  NOT NULL,
    status        VARCHAR(20)  NOT NULL,
    started_at    TIMESTAMPTZ  NOT NULL,
    finished_at   TIMESTAMPTZ,
    fetched       INTEGER      NOT NULL DEFAULT 0,
    inserted      INTEGER      NOT NULL DEFAULT 0,
    updated       INTEGER      NOT NULL DEFAULT 0,
    skipped       INTEGER      NOT NULL DEFAULT 0,
    error_message TEXT
);

CREATE INDEX idx_ingestion_jobs_started ON ingestion_jobs (started_at DESC);
